window.REPLAY_DATA = {
 "after_description": "[Contradicted by Notary 2026-07-18] The prior description said \"Transaction amount in USD.\", but the stored values are inconsistent with it (measured median 12795 with integer_share 1.00; described as USD but every value is an integer with median 12795; consistent with integer cents, not dollars). See the Notary evidence dossier before trusting either statement.",
 "before_description": "Transaction amount in USD.",
 "disclosure": "This page is a frozen, reproducible replay of the recorded demo run (run date 2026-07-18), assembled from that run's inputs: the seeded demo warehouse, the captured Claude extractions (replayed verbatim), and Notary's own write-back formatters, plus two separately captured agent answers that are prompt-bound to this evaluation's evidence. Nothing is generated when this page loads. Full local-run instructions live in the repository README.",
 "eval_table_markdown": "| claim type | planted lies | caught | missed | controls | false positives |\n|---|---|---|---|---|---|\n| unit_scale | 4 | 1 | 3 | 2 | 0 |\n| freshness | 2 | 2 | 0 | 0 | 0 |\n| completeness | 3 | 3 | 0 | 0 | 0 |\n| domain_enum | 2 | 2 | 0 | 2 | 0 |\n| deprecation_usage | 1 | 1 | 0 | 0 | 0 |\n| **total** | 12 | 9 | 3 | 4 | 0 |\n\n1 of 17 entries had no extraction (dim_customers.country_code); scored fail-closed: a lie counts as missed, a control is unscored and excluded from the controls and false-positive columns. Not verified.",
 "findings": [
  {
   "claim_text": "Transaction amount in USD.",
   "dossier_markdown": "# Notary evidence dossier\n\n- Asset: urn:li:dataset:(urn:li:dataPlatform:duckdb,fiction_retail.fct_payments,PROD)\n- Field: amount\n- Claim (unit_scale): \"Transaction amount in USD.\"\n- Verdict: CONTRADICTED\n- Run date: 2026-07-18\n- Rationale: described as USD but every value is an integer with median 12795; consistent with integer cents, not dollars\n\n## Description pre-image (before any Notary correction)\n\nTransaction amount in USD.\n\n## Probe SQL\n\n```sql\nselect median(v) as median, avg(case when v is null then null when v = floor(v) then 1.0 else 0.0 end) as integer_share, avg(case when v is null then null when v * 100 = floor(v * 100) then 1.0 else 0.0 end) as centi_integer_share, min(v) as min, max(v) as max, count(v) as row_count, count(*) as rows_scanned, 100000 as scan_limit from (select \"amount\" as v from \"fct_payments\" limit 100000)\n```\n\n## Measurements\n\n```json\n{\n \"unit_claimed\": \"USD\",\n \"median\": 12795.0,\n \"integer_share\": 1.0,\n \"min\": 511.0,\n \"max\": 24952.0,\n \"row_count\": 2000,\n \"probe_sql\": \"select median(v) as median, avg(case when v is null then null when v = floor(v) then 1.0 else 0.0 end) as integer_share, avg(case when v is null then null when v * 100 = floor(v * 100) then 1.0 else 0.0 end) as centi_integer_share, min(v) as min, max(v) as max, count(v) as row_count, count(*) as rows_scanned, 100000 as scan_limit from (select \\\"amount\\\" as v from \\\"fct_payments\\\" limit 100000)\",\n \"rubric\": \"CONTRADICTED iff integer_share == 1.0 and median > 1000; CONFIRMED iff fractional_share >= 0.3 and 0 < median <= 1000; otherwise UNVERIFIABLE; either verdict requires a complete scan (under the scan limit)\"\n}\n```\n\nWritten by Notary (the context lie detector). This dossier is machine-generated evidence; the next agent reading this asset inherits it.\n",
   "field": "amount",
   "rationale": "described as USD but every value is an integer with median 12795; consistent with integer cents, not dollars",
   "verdict": "CONTRADICTED"
  },
  {
   "claim_text": "ISO-4217 currency code, one of {USD, EUR, GBP}.",
   "dossier_markdown": "# Notary evidence dossier\n\n- Asset: urn:li:dataset:(urn:li:dataPlatform:duckdb,fiction_retail.fct_payments,PROD)\n- Field: currency\n- Claim (domain_enum): \"ISO-4217 currency code, one of {USD, EUR, GBP}.\"\n- Verdict: CONFIRMED\n- Run date: 2026-07-18\n- Rationale: complete distinct set ['EUR', 'GBP', 'USD'] over all 2000 rows sits inside the claimed set\n\n## Description pre-image (before any Notary correction)\n\nISO-4217 currency code, one of {USD, EUR, GBP}.\n\n## Probe SQL\n\n```sql\nselect distinct v from (select \"currency\" as v from \"fct_payments\" limit 100000) where v is not null limit 51\n```\n\n## Measurements\n\n```json\n{\n \"claimed_values\": [\n  \"EUR\",\n  \"GBP\",\n  \"USD\"\n ],\n \"observed_values\": [\n  \"EUR\",\n  \"GBP\",\n  \"USD\"\n ],\n \"unexpected_values\": [],\n \"distinct_capped\": false,\n \"rows_scanned\": 2000,\n \"scan_limit\": 100000,\n \"probe_sql\": \"select distinct v from (select \\\"currency\\\" as v from \\\"fct_payments\\\" limit 100000) where v is not null limit 51\",\n \"rubric\": \"CONTRADICTED iff any observed distinct value is outside the claimed set; CONFIRMED iff the complete distinct set was observed (not capped) over a complete input scan (under the scan limit), is non-empty, and is a subset of the claimed set; otherwise UNVERIFIABLE\"\n}\n```\n\nWritten by Notary (the context lie detector). This dossier is machine-generated evidence; the next agent reading this asset inherits it.\n",
   "field": "currency",
   "rationale": "complete distinct set ['EUR', 'GBP', 'USD'] over all 2000 rows sits inside the claimed set",
   "verdict": "CONFIRMED"
  }
 ],
 "repo": "https://github.com/OrionArchitekton/notary",
 "run_date": "2026-07-18",
 "s5": {
  "view1": "The catalog description states that the `amount` column stores transaction amounts in USD. However, I can't verify whether you can trust this description, since the provided catalog contains no validation, profiling, or measured evidence about the `amount` column\u2014and it doesn't reference the table `fiction_retail.fct_payments` at all, so I can't confirm this description applies to that specific table.",
  "view2": "The amount column's original description claiming \"Transaction amount in USD\" is contradicted by the notary evidence, which found that every value is an integer with a median of 12795\u2014consistent with integer cents rather than dollars\u2014so you should not trust that description. In short, the measurements indicate the amounts are likely stored in integer cents, so treat the stated USD-dollar unit as unreliable."
 }
};
